### ISSUE TITLE
[Bug Fix] The Tab Session Manager's 'input' and 'select' fields are unreadable when using a dark GTK Theme on Linux - Here how to fix it

### ISSUE THREAD

**Issue by hasB4K** [sienori/Tab-Session-Manager#240]
Hi,

I am using a Dark GTK Theme on Linux with Firefox. And sadly, it is quite difficult to use this plugin since the background color of the select, and input is almost black with this setup.

I think you would just need to add in the file `Tab-Session-Manager/popup/popup.css` the following:

```css
input, select
{
    background-color: #FFF !important;
}
```

Sadly, I did not directly tested that since it became harder to modify an extension on Firefox (lack of time mostly). However I modified my `userContent.css` in the profile folder of Firefox: `~/.mozilla/firefox/XXXXXXXXXX.default/chrome`, and it works:

```css
@-moz-document url("moz-extension://[...extension-hash...]/popup/popup.html")
{
    input, select
    {
        background-color: #FFF !important;
    }
}
```

Thank you for your great add-on!

Best regards,
